from app.algorithms.risk_engine import (
    RiskLevel,
    RiskWeights,
    RiskThresholds,
    RiskComponent,
    RiskAssessmentResult,
    DEFAULT_WEIGHTS as DEFAULT_RISK_WEIGHTS,
    DEFAULT_THRESHOLDS as DEFAULT_RISK_THRESHOLDS,
    classify_risk,
    calculate_exposure_score,
    calculate_vulnerability_score,
    calculate_coping_capacity_score,
    calculate_multi_hazard_exposure,
    assess_habitation_risk,
    assess_all_habitations,
    get_risk_distribution,
    get_risk_statistics,
)

from app.algorithms.capacity_engine import (
    CapacityStatus,
    InfrastructureStatus,
    CapacityWeights,
    CapacityThresholds,
    InfrastructureAssessment,
    CapacityAssessmentResult,
    DEFAULT_WEIGHTS as DEFAULT_CAPACITY_WEIGHTS,
    DEFAULT_THRESHOLDS as DEFAULT_CAPACITY_THRESHOLDS,
    calculate_utilization,
    assess_infrastructure_component,
    assess_road_connectivity,
    assess_environmental_status,
    calculate_capacity_score,
    determine_capacity_status,
    identify_limiting_factors,
    assess_relocation_site_capacity,
    assess_all_relocation_sites,
    get_capacity_statistics,
)

from app.algorithms.relocation_engine import (
    PriorityLevel,
    SiteSuitability,
    PriorityWeights,
    MatchWeights,
    PriorityThresholds,
    SuitabilityThresholds,
    RelocationPriorityResult,
    SiteRecommendation,
    RelocationRecommendationResult,
    DEFAULT_PRIORITY_WEIGHTS,
    DEFAULT_MATCH_WEIGHTS,
    DEFAULT_PRIORITY_THRESHOLDS,
    DEFAULT_SUITABILITY_THRESHOLDS,
    calculate_distance,
    classify_priority,
    classify_suitability,
    get_priority_label,
    get_suitability_label,
    calculate_priority_score,
    generate_priority_reason,
    calculate_capacity_suitability,
    calculate_infrastructure_suitability,
    calculate_environmental_suitability,
    calculate_accessibility_score,
    calculate_safety_score,
    evaluate_site_match,
    assess_relocation_priority,
    get_all_recommendations,
    assess_all_priorities,
    get_priority_statistics,
)

__all__ = [
    # Risk engine
    "RiskLevel",
    "RiskWeights",
    "RiskThresholds",
    "RiskComponent",
    "RiskAssessmentResult",
    "DEFAULT_RISK_WEIGHTS",
    "DEFAULT_RISK_THRESHOLDS",
    "classify_risk",
    "calculate_exposure_score",
    "calculate_vulnerability_score",
    "calculate_coping_capacity_score",
    "calculate_multi_hazard_exposure",
    "assess_habitation_risk",
    "assess_all_habitations",
    "get_risk_distribution",
    "get_risk_statistics",
    # Capacity engine
    "CapacityStatus",
    "InfrastructureStatus",
    "CapacityWeights",
    "CapacityThresholds",
    "InfrastructureAssessment",
    "CapacityAssessmentResult",
    "DEFAULT_CAPACITY_WEIGHTS",
    "DEFAULT_CAPACITY_THRESHOLDS",
    "calculate_utilization",
    "assess_infrastructure_component",
    "assess_road_connectivity",
    "assess_environmental_status",
    "calculate_capacity_score",
    "determine_capacity_status",
    "identify_limiting_factors",
    "assess_relocation_site_capacity",
    "assess_all_relocation_sites",
    "get_capacity_statistics",
    # Relocation engine
    "PriorityLevel",
    "SiteSuitability",
    "PriorityWeights",
    "MatchWeights",
    "PriorityThresholds",
    "SuitabilityThresholds",
    "RelocationPriorityResult",
    "SiteRecommendation",
    "RelocationRecommendationResult",
    "DEFAULT_PRIORITY_WEIGHTS",
    "DEFAULT_MATCH_WEIGHTS",
    "DEFAULT_PRIORITY_THRESHOLDS",
    "DEFAULT_SUITABILITY_THRESHOLDS",
    "calculate_distance",
    "classify_priority",
    "classify_suitability",
    "get_priority_label",
    "get_suitability_label",
    "calculate_priority_score",
    "generate_priority_reason",
    "calculate_capacity_suitability",
    "calculate_infrastructure_suitability",
    "calculate_environmental_suitability",
    "calculate_accessibility_score",
    "calculate_safety_score",
    "evaluate_site_match",
    "assess_relocation_priority",
    "get_all_recommendations",
    "assess_all_priorities",
    "get_priority_statistics",
]